### ISSUE TITLE
Game logic editor has no nodes in latest update!

### ISSUE THREAD

**Issue by DonFlymoor** [armory3d/armsdk#12]
Using blender 2.82 and updating the SDK leads to this error:
```
Read prefs: C:\Users\Don\AppData\Roaming\Blender Foundation\Blender\2.82\config\userpref.blend
AL lib: (EE) UpdateDeviceParams: Failed to set 48000hz, got 44100hz instead
found bundled python: C:\Program Files\Blender Foundation\Blender 2.82\2.82\python
Traceback (most recent call last):
  File "C:\Users\Don\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\armory.py", line 260, in execute
    start.register(local_sdk=local_sdk)
  File "C:\Users\Don\Documents\blender\Addons\Amory 3D\armsdk//armory/blender\start.py", line 33, in register
    arm.nodes_logic.register()
  File "C:\Users\Don\Documents\blender\Addons\Amory 3D\armsdk//armory/blender\arm\nodes_logic.py", line 196, in register
    register_nodes()
  File "C:\Users\Don\Documents\blender\Addons\Amory 3D\armsdk//armory/blender\arm\nodes_logic.py", line 52, in register_nodes
    layout_items += [NodeItem('NodeReroute'), NodeItem('NodeFrame')]
NameError: name 'NodeItem' is not defined

location: C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py:201

location: C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py:201
Error: Traceback (most recent call last):
  File "C:\Users\Don\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\armory.py", line 260, in execute
    start.register(local_sdk=local_sdk)
  File "C:\Users\Don\Documents\blender\Addons\Amory 3D\armsdk//armory/blender\start.py", line 33, in register
    arm.nodes_logic.register()
  File "C:\Users\Don\Documents\blender\Addons\Amory 3D\armsdk//armory/blender\arm\nodes_logic.py", line 196, in register
    register_nodes()
  File "C:\Users\Don\Documents\blender\Addons\Amory 3D\armsdk//armory/blender\arm\nodes_logic.py", line 52, in register_nodes
    layout_items += [NodeItem('NodeReroute'), NodeItem('NodeFrame')]
NameError: name 'NodeItem' is not defined

location: C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py:201

Traceback (most recent call last):
  File "C:\Users\Don\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\armory.py", line 380, in on_load_post
    bpy.ops.arm_addon.start()
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\Don\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\armory.py", line 260, in execute
    start.register(local_sdk=local_sdk)
  File "C:\Users\Don\Documents\blender\Addons\Amory 3D\armsdk//armory/blender\start.py", line 33, in register
    arm.nodes_logic.register()
  File "C:\Users\Don\Documents\blender\Addons\Amory 3D\armsdk//armory/blender\arm\nodes_logic.py", line 196, in register
    register_nodes()
  File "C:\Users\Don\Documents\blender\Addons\Amory 3D\armsdk//armory/blender\arm\nodes_logic.py", line 52, in register_nodes
    layout_items += [NodeItem('NodeReroute'), NodeItem('NodeFrame')]
NameError: name 'NodeItem' is not defined

location: C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py:201


Warning: property 'release_confirm' not found in keymap item 'OperatorProperties'
```

**Comment by luboslenco** [comment]
Please check the fix at https://github.com/armory3d/armory/pull/1741.
